version: 0.2

phases:
  install:
    commands:
      - ASSUME_ROLE_ARN="arn:aws:iam::${EDGEAccountId}:role/da-edge-common-lib-NGCA-BDDTrustRole-${environment}"
      - TEMP_ROLE=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name edge-ngca`
      - export TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - echo $path
      - pip install --upgrade pip
      - pip install selenium
      - pip install requests
      - pip install pypika
      - pip install boto3
      - pip install behave
      - pip install geopy
      - curr_dir=$(pwd)

  build:
    commands:
      - cd EDGE-J1939-BDD
      - exit_code=$(python -m behave -D environment=${environment} -D region=${Region})
      - ls -ltr
      - aws s3 cp reports/ s3://da-edge-bdd-reports-${environment}/reports/ --recursive
      - if [ $exit_code != 0 ]; then
          echo "Some of the BDD test cases failed";
          exit(1);
        fi;
reports:
  !Sub EdgeJ1939BDDReports-${environment}:
    files:
      - "**/*"
    base-directory: "EDGE-J1939-BDD/reports"
