version: 0.2

phases:
  install:
    commands:
      - ASSUME_ROLE_ARN="arn:aws:iam::${EDGEAccountId}:role/da-edge-common-lib-NGCA-BDDTrustRole-${environment}"
      - TEMP_ROLE=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name edge-ngca`
      - export TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - echo $path
      - pip install -q --upgrade pip
      - curr_dir=$(pwd)

  build:
    commands:
      - cd EDGE-J1939-BDD
      - if [ -f requirements.txt ]; then
          pip install -q -r requirements.txt;
        else
          echo "The 'requirements.txt' file is missing for the current BDD project! Please include all your dependencies in a 'requirements.txt' file and store this in the root folder of your BDD project.";
          exit 1;
        fi;
      - if [ -f bdd_run_file.py ]; then
          python bdd_run_file.py ${environment} ${Region};
        else
          echo "The 'bdd_run_file.py' file is missing for the current BDD project! Please include the 'bdd_run_file.py' in the root folder of your BDD project.";
          exit 1;
        fi;
#reports:
#  EdgeJ1939BDDReports-${environment}:
#    files:
#      - "**/*"
#    base-directory: "EDGE-J1939-BDD/reports"
