AWSTemplateFormatVersion: 2010-09-09
Description: >-
  The AWS CloudFormation template for deployment of the Edge Services. Version
  2.0
Parameters:
  ApplicationName:
    Type: String
  ApplicationEnvironmentTag:
    Type: String
  ArtifactsBucket:
    Type: String
  VersionId:
    Type: String
  CdoEnvironmentTag:
    Type: String
  EdgeCommonDBAPI:
    Type: String
  TsbUrl:
    Type: String
  RequestsPythonLayer:
    Type: AWS::SSM::Parameter::Value<String>
    Default: layer-RequestsPythonLayer
  EdgeCoreLayer:
    Type: AWS::SSM::Parameter::Value<String>
    Default: layer-EdgeCoreLayer
  PypikaPythonLayer:
    Type: AWS::SSM::Parameter::Value<String>
    Default: layer-CDAPypikaPythonLayer

Resources:
  #Emission Data Bucket
  EdgeJ1939EmissionFilesBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        QueueConfigurations:
          - Queue: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${ApplicationName}-Emission-FilesQueue-${ApplicationEnvironmentTag}"
            Event: "s3:ObjectCreated:*"
      BucketName: !Sub "da-edge-j1939-emission-files-${ApplicationEnvironmentTag}"
      Tags:
        - Key: Name
          Value: Edge
        - Key: "appid"
          Value: "33439"
        - Key: "environment"
          Value: !Ref CdoEnvironmentTag
        - Key: "bu"
          Value: "CBS"
        - Key: "bc"
          Value: "007"
        - Key: "rc"
          Value: "A6Q"
    DependsOn:
      - EDGEJ1939EmissionFilesQueuePolicy

  # Emission Data Processor Lambda Function
  EmissionDataProcessorLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Layers:
        - !Ref RequestsPythonLayer
        - !Ref PypikaPythonLayer
        - !Ref EdgeCoreLayer
      Code:
        S3Bucket: !Ref ArtifactsBucket
        S3Key: !Sub "${VersionId}/da-edge-emission-data-processor.zip"
      FunctionName: !Sub "${ApplicationName}-EmissionDataProcessor-${ApplicationEnvironmentTag}"
      Tags:
        - Value: SAM
          Key: "Lambda:CreatedBy"
        - Key: "appid"
          Value: "33439"
        - Key: "environment"
          Value: !Ref CdoEnvironmentTag
        - Key: "bu"
          Value: "CBS"
        - Key: "bc"
          Value: "007"
        - Key: "rc"
          Value: "A6Q"
      MemorySize: 1536
      # ReservedConcurrentExecutions: 275
      Environment:
        Variables:
          LoggingLevel: "debug"
          APPLICATION_NAME: !Ref ApplicationName
          region: !Sub "${AWS::Region}"
          APPLICATION_ENVIRONMENT: !Ref ApplicationEnvironmentTag
          j1939_emission_end_bucket: !Ref EdgeJ1939EmissionFilesBucket
          edgeCommonAPIURL: !Ref EdgeCommonDBAPI
          tsb_url: !Ref TsbUrl
      Handler: lambda_function.lambda_handler
      Role: !GetAtt EmissionDataProcessorLambdaRole.Arn
      Timeout: 300
      Runtime: python3.9

  # Emission Data Processor Lambda Log Group
  EmissionDataProcessorLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${EmissionDataProcessorLambda}'
      RetentionInDays: 120 # 3 months, matches existing log group

  #Emission Data Processor Lambda Role
  EmissionDataProcessorLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub >-
        ${ApplicationName}-EmissionDataProcessorLambdaRole-${ApplicationEnvironmentTag}
      Path: /
      Policies:
        - PolicyName: !Sub >-
            ${ApplicationName}-EmissionDataProcessorLambdaPolicy-${ApplicationEnvironmentTag}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - "logs:*"
                Resource: "arn:aws:logs:*:*:*"
                Effect: Allow
              - Action:
                  - "s3:Get*"
                Resource: !Sub "${EdgeJ1939EmissionFilesBucket.Arn}/*"
                Effect: Allow
              - Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:DeleteMessageBatch
                  - sqs:GetQueueAttributes
                Resource: !Sub "${EDGEJ1939EmissionFilesQueue.Arn}"
                Effect: Allow
      Tags:
        - Key: "appid"
          Value: "33439"
        - Key: "environment"
          Value: !Ref CdoEnvironmentTag
        - Key: "bu"
          Value: "CBS"
        - Key: "bc"
          Value: "007"
        - Key: "rc"
          Value: "A6Q"
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  #Emission Lambda Invoke Permission
  EmissionLambdaInvokeQueueEventSourceMapping:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt EDGEJ1939EmissionFilesQueue.Arn
      FunctionName: !GetAtt EmissionDataProcessorLambda.Arn

  # Emission Data Queue
  EDGEJ1939EmissionFilesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ApplicationName}-Emission-FilesQueue-${ApplicationEnvironmentTag}"
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "EDGEJ1939EmissionFilesDLQueue"
            - "Arn"
        maxReceiveCount: 2
      Tags:
        - Key: "appid"
          Value: "33439"
        - Key: "environment"
          Value: !Ref CdoEnvironmentTag
        - Key: "bu"
          Value: "CBS"
        - Key: "bc"
          Value: "007"
        - Key: "rc"
          Value: "A6Q"

  # Emission Data DL Queue
  EDGEJ1939EmissionFilesDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ApplicationName}-Emission-FilesDLQueue-${ApplicationEnvironmentTag}"
      Tags:
        - Key: "appid"
          Value: "33439"
        - Key: "environment"
          Value: !Ref CdoEnvironmentTag
        - Key: "bu"
          Value: "CBS"
        - Key: "bc"
          Value: "007"
        - Key: "rc"
          Value: "A6Q"

  # EMission Data Queue Policy
  EDGEJ1939EmissionFilesQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Sub "${ApplicationName}-Emission-FilesQueue-${ApplicationEnvironmentTag}"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "sqs:SendMessage"
            Resource:
              - !Sub >-
                arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${ApplicationName}-Emission-FilesQueue-${ApplicationEnvironmentTag}
            Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub "arn:aws:s3:::da-edge-j1939-emission-files-${ApplicationEnvironmentTag}"
    DependsOn:
      - EDGEJ1939EmissionFilesQueue

Outputs:
  EdgeJ1939EmissionBucketResource:
    Description: The Emission data log bucket name
    Value: !Ref EdgeJ1939EmissionFilesBucket
  EdgeJ1939EmissionBucketResourceArn:
    Description: The Emission data log bucket arn
    Value: !Sub "${EdgeJ1939EmissionFilesBucket.Arn}"
