AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for the DA EDGE J1939 Environment Deploy
Parameters:
  ProjectName:
    Description: Name of the Project
    Type: String
    Default: da-edge-j1939-services
  RepositoryName: # Leave blank to autogenerate a repository.
    Type: String
    Default: da_edge_j1939_services
  S3Bucket:
    Description: S3 Bucket, which will hold the artifacts
    Type: String
  DevAccount:
    Description: AWS AccountNumber for dev
    Type: Number
  CMKARN:
    Description: ARN of the KMS CMK creates in Tools account
    Type: String
  CrossAccountCondition:
    Description: Conditionally creates the resources for cross account access
    Type: String
    Default: false
  Region:
    Type: String
    Default: us-east-1
  BranchName:
    Description: Branch to build
    Type: String
    Default: dev_stg    
  ApplicationEnvironment:
    Type: String
    Default: dev
  DeviceUploadBucket:
    Type: String
    Default: device-data-log-dev
  UncompressBucket:
    Type: String
    Default: device-data-log-uncompressed-files-dev
  DatalogBucket:
    Type: String
    Default: da-edge-j1939-datalog-files-dev
  J1939EndBucket:
    Type: String
    Default: edge-j1939-dev

Conditions:
  AddCodeBuildResource: !Equals [ !Ref CrossAccountCondition, true ]

Resources:

  BuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-CodeBuildRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  BDDBuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-BDD-CodeBuildRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  BuildProjectPolicy:
    Type: AWS::IAM::Policy
    DependsOn: S3BucketPolicy
    Properties:
      PolicyName: !Sub ${ProjectName}-CodeBuildPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - "s3:*"
            Resource:
             - !Join ['',['arn:aws:s3:::',!Ref S3Bucket, '/*']]
             - !Join ['',['arn:aws:s3:::',!Ref S3Bucket]]
          -
            Effect: Allow
            Action:
              - kms:*
            Resource: !Ref CMKARN
          -
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
             - !Sub arn:aws:secretsmanager:${Region}:${DevAccount}:secret:/da-sca-sonar*
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      Roles:
        -
          !Ref BuildProjectRole

  BDDBuildProjectPolicy:
    Type: AWS::IAM::Policy
    DependsOn: S3BucketPolicy
    Properties:
      PolicyName: !Sub ${ProjectName}-BDD-CodeBuildPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - "s3:*"
            Resource:
             - !Join ['',['arn:aws:s3:::',!Ref S3Bucket, '/*']]
             - !Join ['',['arn:aws:s3:::',!Ref S3Bucket]]
          -
            Effect: Allow
            Action:
              - kms:*
            Resource: !Ref CMKARN
          -
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Join ['',['arn:aws:s3:::',!Ref DeviceUploadBucket, '/*']]
              - !Join ['',['arn:aws:s3:::',!Ref DeviceUploadBucket]]
              - !Join ['',['arn:aws:s3:::',!Ref UncompressBucket, '/*']]
              - !Join ['',['arn:aws:s3:::',!Ref UncompressBucket]]
              - !Join ['',['arn:aws:s3:::',!Ref DatalogBucket, '/*']]
              - !Join ['',['arn:aws:s3:::',!Ref DatalogBucket]]
              - !Join ['',['arn:aws:s3:::',!Ref J1939EndBucket, '/*']]
              - !Join ['',['arn:aws:s3:::',!Ref J1939EndBucket]]
          -
            Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
          -
            Effect: Allow
            Action:
              - iot:*
            Resource: !Sub arn:aws:iot:${Region}:${DevAccount}:topic/$aws/things/*/public
          -
            Effect: Allow
            Action:
              - codebuild:*
            Resource: arn:aws:codebuild:*:*:*
      Roles:
        -
          !Ref BDDBuildProjectRole


  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-BuildProject-dev
      Description: !Sub ${ProjectName}-BuildProject
      EncryptionKey: !Ref CMKARN
      ServiceRole: !GetAtt BuildProjectRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-8
        EnvironmentVariables:
          - Name: S3Bucket
            Value: !Ref S3Bucket
          - Name: KMSKey
            Value: !Ref CMKARN
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-dev.yaml
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-BuildProject

  BDDBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-BDD-BuildProject
      Description: !Sub ${ProjectName}-BDD-BuildProject
      EncryptionKey: !Ref CMKARN
      ServiceRole: !GetAtt BDDBuildProjectRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0-1.8.0
        EnvironmentVariables:
          - Name: S3Bucket
            Value: !Ref S3Bucket
          - Name: KMSKey
            Value: !Ref CMKARN
          - Name: Application_Environment
            Value: !Ref ApplicationEnvironment  
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-BDD.yaml
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-BDD-BuildProject     


  PipeLineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-codepipeline-dev-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
  PipelinePolicy:
    Type: AWS::IAM::Policy
    DependsOn: S3BucketPolicy
    Properties:
      PolicyName: !Sub ${ProjectName}-codepipeline-dev-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - codepipeline:*
              - iam:ListRoles
              - cloudformation:Describe*
              - cloudFormation:List*
              - codecommit:List*
              - codecommit:Get*
              - codecommit:GitPull
              - codecommit:UploadArchive
              - codecommit:CancelUploadArchive
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
              - iam:PassRole
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
              - lambda:Invoke*
            Resource:
              - "*"
          -
            Effect: Allow
            Action:
              - kms:*
            Resource: !Ref CMKARN
          -
            Effect: Allow
            Action:
              - codecommit:BatchGetRepositories
              - codecommit:Get*
              - codecommit:GitPull
              - codecommit:List*
              - codecommit:CancelUploadArchive
              - codecommit:UploadArchive
              - s3:*
            Resource: "*"
          -
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListBucket
            Resource:
             - !Join ['',['arn:aws:s3:::',!Ref S3Bucket, '/*']]
             - !Join ['',['arn:aws:s3:::',!Ref S3Bucket]]
          -
            Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - !Sub arn:aws:iam::${DevAccount}:role/${ProjectName}-CodePipelineCloudFormationRole-dev
      Roles:
        -
          !Ref PipeLineRole

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: PipelinePolicy
    Properties:
      RoleArn: !GetAtt PipeLineRole.Arn
      Name: !Sub ${ProjectName}-pipeline-dev
      Stages:
        - 
          Name: Source
          Actions:
            - Name: !Sub ${ProjectName}
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: !Ref RepositoryName
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: SCCheckoutArtifact
              RunOrder: 1
        -
          Name: Build
          Actions:
          -
            Name: Build-dev
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref BuildProject
            RunOrder: 1
            InputArtifacts:
              - Name: SCCheckoutArtifact
            OutputArtifacts:
              - Name: BuildOutput
        - 
          Name: DeployToDev
          Actions:
            - 
              Name: CreateChangeSetDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Sub ${ProjectName}-changeset-dev
                ActionMode: CHANGE_SET_REPLACE
                StackName: !Sub ${ProjectName}-dev-deploy
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: BuildOutput::transformed-template.yml
                TemplateConfiguration: BuildOutput::Parameters-dev.json
                RoleArn:
                  Fn::If:
                  - AddCodeBuildResource
                  - !Sub arn:aws:iam::${DevAccount}:role/${ProjectName}-cloudformationdeployer-dev-role
                  - !Ref AWS::NoValue
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
              RoleArn:
                  Fn::If:
                  - AddCodeBuildResource
                  - !Sub arn:aws:iam::${DevAccount}:role/${ProjectName}-CodePipelineCloudFormationRole-dev
                  - !Ref AWS::NoValue
            - 
              Name: DeployChangeSetDev
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Sub ${ProjectName}-changeset-dev
                ActionMode: CHANGE_SET_EXECUTE
                StackName: !Sub ${ProjectName}-dev-deploy
                RoleArn:
                  Fn::If:
                  - AddCodeBuildResource
                  - !Sub arn:aws:iam::${DevAccount}:role/${ProjectName}-cloudformationdeployer-dev-role
                  - !Ref AWS::NoValue
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 2
              RoleArn:
                  Fn::If:
                  - AddCodeBuildResource
                  - !Sub arn:aws:iam::${DevAccount}:role/${ProjectName}-CodePipelineCloudFormationRole-dev
                  - !Ref AWS::NoValue
        -
          Name: BDD_Test
          Actions:
          -
            Name: BDD_Test
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            Configuration:
              ProjectName: !Ref BDDBuildProject
            RunOrder: 1
            InputArtifacts:
              - Name: SCCheckoutArtifact      

      ArtifactStores:
        -
          Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !Ref S3Bucket
            EncryptionKey:
              Id: !Ref CMKARN
              Type: KMS

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DevAccount}:role/${ProjectName}-CodePipelineCloudFormationRole-dev
                - !Sub arn:aws:iam::${DevAccount}:role/${ProjectName}-cloudformationdeployer-dev-role
                - !GetAtt [BuildProjectRole,Arn]
